import type { RobotsTxtConfig, BotRule, BotPosture } from '../types.js';
import { MachineTrustConfigError } from '../errors.js';

const ROBOTS_CONTROL_CHARACTERS = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]/;
const ROBOTS_PRODUCT_TOKEN = /^(?:\*|[A-Za-z0-9_-]+)$/;

function assertDirectiveValue(field: string, value: unknown): asserts value is string {
  if (typeof value !== 'string' || ROBOTS_CONTROL_CHARACTERS.test(value)) {
    throw new MachineTrustConfigError(
      'INVALID_ROBOTS_DIRECTIVE',
      `${field} must be a string without control characters.`
    );
  }
}

function assertBotName(value: unknown): asserts value is string {
  if (typeof value !== 'string' || !ROBOTS_PRODUCT_TOKEN.test(value)) {
    throw new MachineTrustConfigError(
      'INVALID_ROBOTS_DIRECTIVE',
      'botName must be * or a product token containing only letters, numbers, underscores, and hyphens.'
    );
  }
}

function assertCrawlDelay(value: unknown): asserts value is number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) {
    throw new MachineTrustConfigError(
      'INVALID_ROBOTS_DIRECTIVE',
      'crawlDelay must be a finite, non-negative number.'
    );
  }
}

export const KNOWN_AI_BOTS = {
  SEARCH: ['OAI-SearchBot', 'PerplexityBot', 'ClaudeBot', 'Googlebot', 'Bingbot', 'Applebot'],
  TRAINING: ['GPTBot', 'Google-Extended', 'anthropic-ai', 'Applebot-Extended', 'CCBot', 'cohere-ai', 'Diffbot', 'Bytespider'],
};

/**
 * Builds standard bot rules based on posture
 */
export function getRulesForPosture(posture: BotPosture = 'allow_ai_search_disallow_training'): BotRule[] {
  switch (posture) {
    case 'allow_ai_search_disallow_training':
      return [
        // AI Search Discovery Bots (Allow)
        { botName: 'OAI-SearchBot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        { botName: 'PerplexityBot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        { botName: 'ClaudeBot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        // Standard Web Indexers (Allow)
        { botName: 'Googlebot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        { botName: 'Bingbot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        { botName: 'Applebot', allow: ['/'], disallow: ['/api/', '/admin/'] },
        // Model Training / Scraper Bots (Disallow)
        { botName: 'GPTBot', disallow: ['/'] },
        { botName: 'Google-Extended', disallow: ['/'] },
        { botName: 'anthropic-ai', disallow: ['/'] },
        { botName: 'CCBot', disallow: ['/'] },
        { botName: 'cohere-ai', disallow: ['/'] },
        { botName: 'Bytespider', disallow: ['/'] },
      ];

    case 'allow_all':
      return [
        { botName: '*', allow: ['/'], disallow: ['/api/', '/admin/'] },
        { botName: 'OAI-SearchBot', allow: ['/'] },
        { botName: 'GPTBot', allow: ['/'] },
        { botName: 'PerplexityBot', allow: ['/'] },
        { botName: 'ClaudeBot', allow: ['/'] },
      ];

    case 'restrict_training_only':
      return [
        { botName: '*', allow: ['/'] },
        { botName: 'GPTBot', disallow: ['/'] },
        { botName: 'Google-Extended', disallow: ['/'] },
        { botName: 'CCBot', disallow: ['/'] },
      ];

    case 'deny_all':
      return [{ botName: '*', disallow: ['/'] }];

    default:
      return [{ botName: '*', allow: ['/'] }];
  }
}

/**
 * Generates formatted robots.txt string
 */
export function generateRobotsTxt(config: RobotsTxtConfig = {}): string {
  const lines: string[] = [];

  if (config.host !== undefined) assertDirectiveValue('host', config.host);
  if (config.sitemapUrl !== undefined) assertDirectiveValue('sitemapUrl', config.sitemapUrl);

  lines.push('# ==============================================================================');
  lines.push('# Robots.txt with Explicit AI Search & Machine Trust Rules');
  lines.push('# Generated by @nymrel/machine-trust');
  lines.push('# ==============================================================================');
  lines.push('');

  // Sitemaps & Host
  if (config.host) {
    lines.push(`Host: ${config.host}`);
  }
  if (config.sitemapUrl) {
    lines.push(`Sitemap: ${config.sitemapUrl}`);
  }
  if (config.host || config.sitemapUrl) {
    lines.push('');
  }

  // Determine Bot Rules
  let rules: BotRule[] = [];
  if (config.botRules && config.botRules.length > 0) {
    rules = config.botRules;
  } else {
    rules = getRulesForPosture(config.posture || 'allow_ai_search_disallow_training');
  }

  // Format bot rules
  for (const rule of rules) {
    assertBotName(rule.botName);
    lines.push(`User-agent: ${rule.botName}`);
    if (rule.crawlDelay !== undefined) {
      assertCrawlDelay(rule.crawlDelay);
      lines.push(`Crawl-delay: ${rule.crawlDelay}`);
    }
    if (rule.allow && rule.allow.length > 0) {
      for (const p of rule.allow) {
        assertDirectiveValue('allow path', p);
        lines.push(`Allow: ${p}`);
      }
    }
    if (rule.disallow && rule.disallow.length > 0) {
      for (const p of rule.disallow) {
        assertDirectiveValue('disallow path', p);
        lines.push(`Disallow: ${p}`);
      }
    }
    lines.push('');
  }

  // Default wildcard rule if not present
  const hasWildcard = rules.some((r) => r.botName === '*');
  if (!hasWildcard) {
    lines.push('User-agent: *');
    const allows = config.defaultAllow || ['/'];
    const disallows = config.defaultDisallow || ['/api/', '/admin/'];
    for (const a of allows) {
      assertDirectiveValue('default allow path', a);
      lines.push(`Allow: ${a}`);
    }
    for (const d of disallows) {
      assertDirectiveValue('default disallow path', d);
      lines.push(`Disallow: ${d}`);
    }
    lines.push('');
  }

  return lines.join('\n').trim() + '\n';
}

export interface ParsedRobotsTxt {
  host?: string;
  sitemaps: string[];
  rules: Record<string, { allow: string[]; disallow: string[]; crawlDelay?: number }>;
}

/**
 * Parses existing robots.txt into structured rule matrix
 */
export function parseRobotsTxt(content: string): ParsedRobotsTxt {
  const lines = content.split('\n');
  const result: ParsedRobotsTxt = {
    sitemaps: [],
    rules: {},
  };

  let currentAgents: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const commentIndex = rawLine.indexOf('#');
    const line = (commentIndex !== -1 ? rawLine.substring(0, commentIndex) : rawLine).trim();

    if (!line) continue;

    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;

    const key = line.substring(0, colonIdx).trim().toLowerCase();
    const value = line.substring(colonIdx + 1).trim();

    if (key === 'host') {
      result.host = value;
    } else if (key === 'sitemap') {
      result.sitemaps.push(value);
    } else if (key === 'user-agent') {
      // If previous line wasn't user-agent, reset currentAgents
      if (i > 0) {
        const prevLine = lines[i - 1].split('#')[0].trim().toLowerCase();
        if (!prevLine.startsWith('user-agent:')) {
          currentAgents = [];
        }
      }
      currentAgents.push(value);
      for (const agent of currentAgents) {
        if (!result.rules[agent]) {
          result.rules[agent] = { allow: [], disallow: [] };
        }
      }
    } else if (key === 'allow') {
      for (const agent of currentAgents) {
        if (result.rules[agent]) {
          result.rules[agent].allow.push(value);
        }
      }
    } else if (key === 'disallow') {
      for (const agent of currentAgents) {
        if (result.rules[agent]) {
          result.rules[agent].disallow.push(value);
        }
      }
    } else if (key === 'crawl-delay') {
      const delay = parseFloat(value);
      for (const agent of currentAgents) {
        if (result.rules[agent]) {
          result.rules[agent].crawlDelay = delay;
        }
      }
    }
  }

  return result;
}
